require('plugins/barbar')
require('plugins/gitsigns')
require('plugins/indent-blankline')
require('plugins/lightline')
-- require('plugins/moonfly')
require('plugins/nerdcommenter')
require('plugins/nvim-tree')
require('plugins/nvim-treesitter')
-- require('plugins/onedark')
require('plugins/telescope')
